services:
  db:
    image: postgres:15-alpine
    container_name: log_anomaly_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=log_db
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d log_db"]
      interval: 5s
      timeout: 5s
      retries: 5
