services:
  db:
    image: postgres:15-alpine
    container_name: log_anomaly_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=log_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d log_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  ingestion:
    build: .
    command: uv run ingestion/consumer.py
    environment:
      - DATABASE_URL=postgresql://admin:secret@db:5432/log_db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started

  producer:
    build: .
    command: uv run producer/main.py
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - kafka

  extractor:
    build: .
    command: uv run features/extractor.py
    environment:
      - DATABASE_URL=postgresql://admin:secret@db:5432/log_db
    depends_on:
      db:
        condition: service_healthy

  alert-service:
    build: .
    command: uv run alert/main.py
    environment:
      - DATABASE_URL=postgresql://admin:secret@db:5432/log_db
    depends_on:
      db:
        condition: service_healthy

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
